<?php
// Path: src/core/Mailer.php

$autoloadPath = dirname(__DIR__, 2) . '/vendor/autoload.php';
if (file_exists($autoloadPath)) {
    require_once $autoloadPath;
}

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

if (!function_exists('env_value')) {
    function env_value(string $key, ?string $default = null): ?string
    {
        if (array_key_exists($key, $_ENV)) return (string)$_ENV[$key];
        $value = getenv($key);
        return $value === false ? $default : (string)$value;
    }
}

/**
 * Shared internal mail dispatcher handling SMTP and PHPMailer configuration.
 *
 * @param string $toEmail Recipient email address
 * @param string $toName Recipient display name (raw string; MIME-encoded by PHPMailer)
 * @param string $subject Email subject line
 * @param string $htmlBody Rendered HTML email body (dynamic variables must be HTML-escaped)
 * @param string|null $altBody Plain-text email body (must NOT be HTML-escaped)
 * @param PHPMailer|null &$mailOut Optional output reference to the prepared PHPMailer instance (for testing/inspection)
 * @param bool $send Whether to invoke $mail->send() (default true; set false for testing/dry-runs)
 * @return bool True on success, false on failure
 */
function send_mail(
    string $toEmail,
    string $toName,
    string $subject,
    string $htmlBody,
    ?string $altBody = null,
    ?PHPMailer &$mailOut = null,
    bool $send = true
): bool {
    $autoloadPath = dirname(__DIR__, 2) . '/vendor/autoload.php';
    if (!file_exists($autoloadPath)) {
        throw new RuntimeException('Mail dependencies not installed. Run composer install.');
    }
    require_once $autoloadPath;

    if (!class_exists('PHPMailer\\PHPMailer\\PHPMailer')) {
        throw new RuntimeException('Mail dependencies not installed. Run composer install.');
    }

    $host = env_value('MAIL_HOST');
    $fromAddress = env_value('MAIL_FROM_ADDRESS');

    if (empty($host) || empty($fromAddress)) {
        throw new RuntimeException('Mail is not configured. Set MAIL_* variables in .env.');
    }

    $port = (int) env_value('MAIL_PORT', '587');
    if ($port < 1 || $port > 65535) {
        $port = 587;
    }

    $username = env_value('MAIL_USERNAME', '');
    $password = env_value('MAIL_PASSWORD', '');
    $encryption = strtolower((string) env_value('MAIL_ENCRYPTION', 'tls'));
    $fromName = env_value('MAIL_FROM_NAME', 'InternBoot');

    $mail = new PHPMailer(true);

    try {
        $mail->isSMTP();
        $mail->Host       = $host;
        $mail->SMTPAuth   = !empty($username);
        if (!empty($username)) {
            $mail->Username   = $username;
            $mail->Password   = $password;
        }

        if ($encryption === 'ssl') {
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;
        } elseif ($encryption === 'tls') {
            $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
        } else {
            $mail->SMTPSecure = '';
            $mail->SMTPAutoTLS = false;
        }

        $mail->Port       = $port;
        $mail->Timeout    = 5;

        $mail->setFrom($fromAddress, $fromName);
        $mail->addAddress($toEmail, $toName);

        $mail->isHTML(true);
        $mail->Subject = $subject;
        $mail->Body    = $htmlBody;
        if ($altBody !== null) {
            $mail->AltBody = $altBody;
        }

        $mailOut = $mail;

        if ($send) {
            $mail->send();
        }
        return true;
    } catch (Exception $e) {
        error_log("Mailer Error: {$mail->ErrorInfo} | Exception: {$e->getMessage()}");
        return false;
    } catch (Throwable $e) {
        error_log("Mailer Unexpected Error: {$e->getMessage()}");
        return false;
    }
}

/**
 * Sends a registration/verification OTP email with safely escaped dynamic values.
 *
 * @param string $toEmail Recipient email address
 * @param string $toName Recipient name (untrusted user input, escaped for HTML)
 * @param string $otp 6-digit verification code
 * @param PHPMailer|null &$mailOut Optional output reference to PHPMailer instance
 * @param bool $send Whether to invoke send()
 * @return bool
 */
function send_otp_email(string $toEmail, string $toName, string $otp, ?PHPMailer &$mailOut = null, bool $send = true): bool {
    // Escape untrusted user-supplied name to prevent HTML injection / phishing links
    $safeName = htmlspecialchars($toName, ENT_QUOTES, 'UTF-8');

    // $otp is generated by random_int(100000, 999999) and is strictly a 6-digit integer string,
    // so it contains only [0-9] and cannot contain HTML-special characters. We also apply htmlspecialchars
    // as defense-in-depth against future changes to code format.
    $safeOtp = htmlspecialchars($otp, ENT_QUOTES, 'UTF-8');

    $subject = 'Your InternBoot verification code';
    $htmlBody = "
        <div style='font-family: Arial, sans-serif; max-width: 480px; margin: 0 auto;'>
            <h2 style='color:#2F6FEB;'>InternBoot Email Verification</h2>
            <p>Hi {$safeName},</p>
            <p>Your verification code is:</p>
            <div style='font-size: 32px; font-weight: 800; letter-spacing: 8px; color: #1E4FD1; margin: 20px 0;'>{$safeOtp}</div>
            <p>This code expires in 10 minutes. If you didn't request this, you can safely ignore this email.</p>
        </div>
    ";

    // Plain-text alternative must NOT be HTML-escaped to avoid showing raw entities in plain-text clients
    $altBody = "Your InternBoot verification code is: {$otp} (expires in 10 minutes)";

    return send_mail($toEmail, $toName, $subject, $htmlBody, $altBody, $mailOut, $send);
}

/**
 * Sends a password reset email with safely escaped dynamic values.
 *
 * @param string $toEmail Recipient email address
 * @param string $toName Recipient name (untrusted user input, escaped for HTML)
 * @param string $resetLink Password reset URL (escaped in both href and link text)
 * @param PHPMailer|null &$mailOut Optional output reference to PHPMailer instance
 * @param bool $send Whether to invoke send()
 * @return bool
 */
function send_password_reset_email(string $toEmail, string $toName, string $resetLink, ?PHPMailer &$mailOut = null, bool $send = true): bool {
    // Escape untrusted user-supplied name to prevent HTML injection / phishing links
    $safeName = htmlspecialchars($toName, ENT_QUOTES, 'UTF-8');

    // Escape reset link in both href attribute and displayed text for defense-in-depth
    $safeResetLink = htmlspecialchars($resetLink, ENT_QUOTES, 'UTF-8');

    $subject = 'Reset your InternBoot password';
    $htmlBody = "
        <div style='font-family: Arial, sans-serif; max-width: 480px; margin: 0 auto;'>
            <h2 style='color:#2F6FEB;'>Reset your password</h2>
            <p>Hi {$safeName},</p>
            <p>Click the link below to reset your InternBoot password. This link expires in 30 minutes.</p>
            <p><a href='{$safeResetLink}' style='background:#1E4FD1;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;'>Reset Password</a></p>
            <p style='font-size: 13px; color: #64748b; word-break: break-all;'>Or copy and paste this link into your browser:<br><a href='{$safeResetLink}'>{$safeResetLink}</a></p>
            <p>If you didn't request this, you can safely ignore this email.</p>
        </div>
    ";

    // Plain-text alternative must NOT be HTML-escaped to avoid showing raw entities in plain-text clients
    $altBody = "Reset your InternBoot password: {$resetLink} (expires in 30 minutes)";

    return send_mail($toEmail, $toName, $subject, $htmlBody, $altBody, $mailOut, $send);
}
?>